"""Add image_file_id column to mailings

Revision ID: 45f38b1e1e6c
Revises: 754bf9822264
Create Date: 2025-11-07 09:11:55.774090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45f38b1e1e6c'
down_revision: Union[str, None] = '754bf9822264'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mailings', sa.Column('image_file_id', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mailings', 'image_file_id')
    # ### end Alembic commands ###
