"""update models MailingORM (delete 'last_sent')

Revision ID: 7dcba5eb3a33
Revises: 26e2dd624c0d
Create Date: 2025-10-10 19:23:43.466354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dcba5eb3a33'
down_revision: Union[str, None] = '26e2dd624c0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mailings', 'last_sent')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mailings', sa.Column('last_sent', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::real"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
