"""update models MailingORM

Revision ID: 916b7460b960
Revises: 8ce05b091b10
Create Date: 2025-10-10 18:49:40.460453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '916b7460b960'
down_revision: Union[str, None] = '8ce05b091b10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mailings', sa.Column('scheduled_date', sa.Date(), nullable=False))
    op.add_column('mailings', sa.Column('channel_id', sa.Integer(), nullable=False))
    op.alter_column('mailings', 'last_sent',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'::real"))
    op.drop_index(op.f('ix_mailing_schedule_enabled'), table_name='mailings')
    op.create_index('ix_mailing_schedule_enabled', 'mailings', ['scheduled_date', 'hour', 'minute', 'enabled', 'channel_id'], unique=False)
    op.drop_column('mailings', 'channel_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mailings', sa.Column('channel_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index('ix_mailing_schedule_enabled', table_name='mailings')
    op.create_index(op.f('ix_mailing_schedule_enabled'), 'mailings', ['hour', 'minute', 'enabled'], unique=False)
    op.alter_column('mailings', 'last_sent',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'::real"))
    op.drop_column('mailings', 'channel_id')
    op.drop_column('mailings', 'scheduled_date')
    # ### end Alembic commands ###
